#!/usr/bin/env python3
"""Compare the running environment against a frozen run's provenance header.

  python common/scripts/check_env_matches_frozen.py results/scvd-phase2/raw/<any>.jsonl
  python common/scripts/check_env_matches_frozen.py <log> --emit-pins hpc/frozen-libs.txt

A repair run is only comparable with the frozen run if it differs from it in
the one intended way. The inference libraries are not a detail: ultralytics
drives local-gpu and remote, onnxruntime drives edge-sim, and a minor version
bump can move both detections and timing. Without this check the equivalence
test of docs/RERUN-PREREGISTRACE.md would silently be testing "the mediamtx
fix AND a library upgrade", and a failure could not be attributed.

Exit status is 0 only when every library the frozen header recorded is
present at the same version. Libraries the frozen header did NOT record (torch
and torchvision, before 2026-08-03) are reported as unknown and do not fail the
check -- there is nothing to compare against, and pretending otherwise would be
worse than saying so.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# module name -> pip package name (they differ for cv2)
#
# cv2 maps to opencv-python, NOT opencv-python-headless. The raw log records a
# runtime module version and cannot say which distribution provided it, and two
# of them can be installed at once: ultralytics pulls opencv-python while this
# package pins opencv-python-headless<5. The frozen run logged cv2 5.0.0, which
# only opencv-python ships -- pinning the headless package to 5.x produced a
# constraints file that could never be satisfied, because our own dependency
# caps it below 5. That made setup_venv.sh unable to build the environment on a
# new machine; found when standing up Karolina, 2026-08-27.
PACKAGE = {
    "numpy": "numpy",
    "cv2": "opencv-python",
    "scipy": "scipy",
    "pandas": "pandas",
    "ultralytics": "ultralytics",
    "onnxruntime": "onnxruntime",
    "torch": "torch",
    "torchvision": "torchvision",
}


def installed(mod: str) -> str:
    try:
        return getattr(__import__(mod), "__version__", "unknown")
    except ImportError:
        return "not-installed"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("frozen_log", help="any raw .jsonl from the frozen run")
    ap.add_argument("--emit-pins", metavar="FILE",
                    help="write a pip constraints file reproducing the frozen versions")
    args = ap.parse_args()

    with open(args.frozen_log) as f:
        header = json.loads(f.readline())
    frozen = header["libs"]

    print(f"frozen run: git {header.get('git_hash', '?')[:7]} "
          f"config {header.get('config_hash', '?')} on {header.get('hostname', '?')}")
    print()
    print(f"  {'knihovna':16s} {'zmrazeny beh':>16s} {'zde':>16s}   stav")

    bad = []
    for mod in ["python"] + [m for m in PACKAGE if m != "python"]:
        want = frozen.get(mod)
        have = sys.version.split()[0] if mod == "python" else installed(mod)
        if want is None:
            state = "nezaznamenano"          # frozen header predates this field
        elif want == have:
            state = "OK"
        else:
            state = "!! LISI SE"
            bad.append((mod, want, have))
        print(f"  {mod:16s} {want or '-':>16s} {have:>16s}   {state}")

    if args.emit_pins:
        lines = []
        for mod, pkg in PACKAGE.items():
            want = frozen.get(mod)
            if not want or want in ("unknown", "not-installed"):
                continue
            # cv2.__version__ has three components, the wheel has four
            lines.append(f"{pkg}~={want}.0" if mod == "cv2" else f"{pkg}=={want}")
        out = Path(args.emit_pins)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(
            "# Generated by common/scripts/check_env_matches_frozen.py from\n"
            f"# {args.frozen_log}\n"
            f"# frozen run: git {header.get('git_hash','?')[:7]}, "
            f"config_hash {header.get('config_hash','?')}\n"
            "# Do not hand-edit: regenerate from the frozen log.\n"
            + "\n".join(lines) + "\n"
        )
        print(f"\npins -> {out}")

    print()
    if bad:
        print(f"NEPROSLO: {len(bad)} knihoven se lisi od zmrazeneho behu")
        for mod, want, have in bad:
            print(f"  {PACKAGE.get(mod, mod)}: {have} -> potreba {want}")
        return 1
    print("OK — prostredi odpovida zmrazenemu behu")
    return 0


if __name__ == "__main__":
    sys.exit(main())
